# Generated by Django 4.2.11 on 2025-12-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimiento_anulado_movimiento_anulado_motivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toner',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='toner',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='toner',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='toner',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='toner',
            name='minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toner',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='toner',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
