# Generated by Django 4.2.11 on 2025-12-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_toner_options_alter_toner_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toner',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
