# Generated by Django 6.0 on 2026-01-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_toner_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('codigo', models.CharField(blank=True, default='', max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='toner',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='nro_nota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='nro_pedido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='MovimientoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.articulo')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='inventario.movimiento')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoToner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toners', to='inventario.movimiento')),
                ('toner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.toner')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
