# Generated by Django 6.0 on 2026-01-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_articulo_remove_movimiento_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toner',
            options={'ordering': ['modelo']},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='toner',
            name='codigo',
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ubicacion',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad',
            field=models.CharField(blank=True, default='u', max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='nro_orden_provision',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='minimo',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='toner',
            name='minimo',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='toner',
            name='stock',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['nombre'], name='inventario__nombre_d8f8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['categoria'], name='inventario__categor_d45dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['-fecha'], name='inventario__fecha_485921_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo'], name='inventario__tipo_85c477_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['anulado'], name='inventario__anulado_64e379_idx'),
        ),
        migrations.AddIndex(
            model_name='toner',
            index=models.Index(fields=['modelo'], name='inventario__modelo_f61b7d_idx'),
        ),
    ]
