# Generated by Django 6.0 on 2026-01-08 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_toner_options_remove_articulo_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pc', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('patrimonio', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('caracteristicas', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PEDIDO', 'Pedido'), ('NOTA', 'Nota'), ('ORDEN', 'Orden de Provisión')], max_length=20)),
                ('numero', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('patrimonio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(default='ACTIVA', max_length=50)),
                ('conexion', models.CharField(choices=[('IP', 'Red'), ('USB', 'USB')], max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TONER', 'Toner'), ('ARTICULO', 'Artículo'), ('ACTIVO_PC', 'PC')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movimientoarticulo',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='movimientoarticulo',
            name='movimiento',
        ),
        migrations.RemoveField(
            model_name='movimientotoner',
            name='movimiento',
        ),
        migrations.RemoveField(
            model_name='movimientotoner',
            name='toner',
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='toner',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='articulo',
            name='inventario__nombre_d8f8d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='articulo',
            name='inventario__categor_d45dcf_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='inventario__fecha_485921_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='inventario__tipo_85c477_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='inventario__anulado_64e379_idx',
        ),
        migrations.RemoveIndex(
            model_name='toner',
            name='inventario__modelo_f61b7d_idx',
        ),
        migrations.RenameField(
            model_name='toner',
            old_name='modelo',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='articulo',
            name='caracteristicas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='toner',
            name='modelo_impresora',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.servicio'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('AJUSTE', 'Ajuste')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='toner',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activopc',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('tipo', 'numero')},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.documento'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.servicio'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='toner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.toner'),
        ),
        migrations.AddField(
            model_name='item',
            name='activo_pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.activopc'),
        ),
        migrations.AddField(
            model_name='item',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='item',
            name='toner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.toner'),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.item'),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.movimiento'),
        ),
        migrations.DeleteModel(
            name='MovimientoArticulo',
        ),
        migrations.DeleteModel(
            name='MovimientoToner',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='minimo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='anulado',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='anulado_motivo',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='entregado_a',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='nro_nota',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='nro_orden_provision',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='nro_pedido',
        ),
        migrations.RemoveField(
            model_name='toner',
            name='minimo',
        ),
        migrations.RemoveField(
            model_name='toner',
            name='stock',
        ),
    ]
