# Generated by Django 6.0 on 2026-01-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_activopc_documento_impresora_item_movimientodetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
