# Generated by Django 6.0 on 2026-01-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_impresora_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='impresora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.impresora'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('TONER', 'Toner'), ('ARTICULO', 'Artículo'), ('ACTIVO_PC', 'Activo PC'), ('IMPRESORA', 'Impresora')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('AJUSTE', 'Ajuste')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movimientodetalle',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.item'),
        ),
    ]
