# Generated by Django 6.0 on 2026-01-14 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_item_impresora_movimiento_anulado_alter_item_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoProyector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_contacto', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_retiro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion_estimada', models.DateField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('incluye_prolongacion', models.BooleanField(default=False)),
                ('incluye_pc', models.BooleanField(default=False)),
                ('incluye_notebook', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.servicio')),
            ],
        ),
    ]
