# Generated by Django 6.0 on 2026-01-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_pendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ENVIADO', 'Enviado'), ('EN_REPARACION', 'En reparación'), ('LISTO', 'Listo'), ('RETIRADO', 'Retirado'), ('CERRADO', 'Cerrado')], default='RECIBIDO', max_length=20)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_retorno', models.DateField(blank=True, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=255)),
                ('seguimiento', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='inventario.item')),
            ],
        ),
    ]
