# Generated by Django 6.0 on 2026-01-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_reparacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reparacion',
            options={'ordering': ['-creado']},
        ),
        migrations.AddField(
            model_name='reparacion',
            name='proveedor_contacto',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
