# Generated by Django 6.0 on 2026-01-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='proveedor_contacto',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='proveedor_nombre',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones', to='inventario.proveedor'),
        ),
    ]
