# Generated by Django 5.2.10 on 2026-01-22 15:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_remove_reparacion_proveedor_contacto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.CharField(max_length=50, unique=True)),
                ('detalle_item', models.CharField(blank=True, max_length=255)),
                ('serial', models.CharField(blank=True, max_length=80)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('numero_nota', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('para_que', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('HECHO', 'Hecho'), ('APROBADO', 'Aprobado'), ('RECIBIDO', 'Recibido'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], db_index=True, default='HECHO', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('detalle', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activopc',
            options={'ordering': ['nombre_pc']},
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha', 'tipo', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='impresora',
            options={'ordering': ['marca', 'modelo']},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='prestamoproyector',
            options={'ordering': ['-fecha_retiro']},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='toner',
            options={'ordering': ['nombre', 'marca']},
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='activopc',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_pc', to='inventario.servicio'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impresoras', to='inventario.servicio'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='toner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impresoras', to='inventario.toner'),
        ),
        migrations.AlterField(
            model_name='item',
            name='activo_pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.activopc'),
        ),
        migrations.AlterField(
            model_name='item',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='impresora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.impresora'),
        ),
        migrations.AlterField(
            model_name='item',
            name='toner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.toner'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.documento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.servicio'),
        ),
        migrations.AlterField(
            model_name='movimientodetalle',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='prestamoproyector',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_proyector', to='inventario.servicio'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('tipo', 'numero'), name='uniq_documento_tipo_numero'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('toner__isnull', False), ('articulo__isnull', True), ('activo_pc__isnull', True), ('impresora__isnull', True)), models.Q(('toner__isnull', True), ('articulo__isnull', False), ('activo_pc__isnull', True), ('impresora__isnull', True)), models.Q(('toner__isnull', True), ('articulo__isnull', True), ('activo_pc__isnull', False), ('impresora__isnull', True)), models.Q(('toner__isnull', True), ('articulo__isnull', True), ('activo_pc__isnull', True), ('impresora__isnull', False)), _connector='OR'), name='chk_item_exactamente_un_fk'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('toner__isnull', False)), fields=('tipo', 'toner'), name='uniq_item_toner'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('articulo__isnull', False)), fields=('tipo', 'articulo'), name='uniq_item_articulo'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('activo_pc__isnull', False)), fields=('tipo', 'activo_pc'), name='uniq_item_activo_pc'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('impresora__isnull', False)), fields=('tipo', 'impresora'), name='uniq_item_impresora'),
        ),
        migrations.AddField(
            model_name='patrimoniounidad',
            name='asignado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patrimoniounidad',
            name='servicio_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios_asignados', to='inventario.servicio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicio_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='inventario.servicio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.item'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.pedido'),
        ),
        migrations.AddField(
            model_name='patrimoniounidad',
            name='pedido_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonios', to='inventario.pedidodetalle'),
        ),
        migrations.AddIndex(
            model_name='pedidodetalle',
            index=models.Index(fields=['pedido'], name='inventario__pedido__6949aa_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidodetalle',
            index=models.Index(fields=['item'], name='inventario__item_id_bf6697_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.UniqueConstraint(fields=('pedido', 'item'), name='uniq_pedido_item'),
        ),
        migrations.AddIndex(
            model_name='patrimoniounidad',
            index=models.Index(fields=['pedido_detalle'], name='inventario__pedido__23f579_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimoniounidad',
            index=models.Index(fields=['servicio_asignado'], name='inventario__servici_41d166_idx'),
        ),
    ]
