# Generated by Django 5.2.10 on 2026-01-26 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_patrimoniounidad_pedido_pedidodetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_contacto', models.CharField(blank=True, default='', max_length=50)),
                ('entregado_a', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_retiro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion_estimada', models.DateField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='inventario.servicio')),
            ],
            options={
                'ordering': ['-fecha_retiro'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('detalle', models.CharField(blank=True, default='', max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_detalle', to='inventario.item')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.prestamo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='PrestamoProyector',
        ),
    ]
