# Generated by Django 5.2.10 on 2026-01-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_prestamo_prestamodetalle_delete_prestamoproyector'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categoria_prestamo',
            field=models.CharField(blank=True, choices=[('PROYECTOR', 'Proyector'), ('WEBCAM', 'Cámara web'), ('NOTEBOOK', 'Notebook'), ('PROLONGACION', 'Prolongación'), ('OTRO', 'Otro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='prestable',
            field=models.BooleanField(default=False),
        ),
    ]
