# Generated by Django 5.2.10 on 2026-01-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_item_categoria_prestamo_item_prestable'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='camara_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='notebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='prolongacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='proyector',
            field=models.BooleanField(default=False),
        ),
    ]
