# Generated by Django 5.2.10 on 2026-01-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_prestamo_camara_web_prestamo_notebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='solicitado_por',
        ),
    ]
