# Generated by Django 5.2.10 on 2026-01-29 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_remove_pedido_solicitado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='inventario.servicio'),
        ),
    ]
