# Generated by Django 5.2.10 on 2026-01-30 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_reparacion_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impresora',
            name='servicio',
        ),
        migrations.CreateModel(
            name='AsignacionImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(default=django.utils.timezone.now)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=100)),
                ('responsable', models.CharField(blank=True, default='', max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='inventario.impresora')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impresoras_asignadas', to='inventario.servicio')),
            ],
            options={
                'ordering': ['-fecha_desde'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_hasta__isnull', True)), fields=('impresora',), name='uniq_asignacion_activa_por_impresora')],
            },
        ),
    ]
