# Generated by Django 5.2.10 on 2026-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_remove_impresora_servicio_asignacionimpresora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendiente',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
