# Generated by Django 5.2.10 on 2026-02-24 14:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_pendiente_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default='', max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('detalle', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('servicio_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='inventario.servicio')),
            ],
            options={
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='NotaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('detalle', models.CharField(blank=True, default='', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.item')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.nota')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['estado'], name='inventario__estado_027740_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['fecha'], name='inventario__fecha_90c608_idx'),
        ),
        migrations.AddConstraint(
            model_name='notadetalle',
            constraint=models.UniqueConstraint(fields=('nota', 'item'), name='uniq_nota_item'),
        ),
    ]
