# Generated by Django 5.2.10 on 2026-02-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_nota_notadetalle_nota_inventario__estado_027740_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
