# Generated by Django 5.2.10 on 2026-02-25 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_nota_fecha_cierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item_hijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_combos', to='inventario.item')),
                ('item_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='inventario.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item_padre', 'item_hijo'), name='uniq_combo_componente'), models.CheckConstraint(condition=models.Q(('item_padre', models.F('item_hijo')), _negated=True), name='chk_no_auto_referencia')],
            },
        ),
    ]
