# Generated by Django 5.2.10 on 2026-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_itemcomponente'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='es_combo',
            field=models.BooleanField(default=False),
        ),
    ]
