# Generated by Django 5.2.1 on 2026-06-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0029_refactor_prestamo_pendiente"),
    ]

    operations = [
        migrations.AddField(
            model_name="patrimoniounidad",
            name="ip",
            field=models.CharField(
                blank=True, max_length=45, verbose_name="Dirección IP"
            ),
        ),
        migrations.AddField(
            model_name="patrimoniounidad",
            name="nombre_pc",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Nombre del equipo"
            ),
        ),
        migrations.AddField(
            model_name="patrimoniounidad",
            name="usuario_asignado",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Usuario asignado"
            ),
        ),
    ]
