# Generated by Django 5.2.1 on 2026-06-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0030_patrimonio_pc_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="fecha_aprobado",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha aprobación"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_entregado",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha entrega"),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_recibido",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha recepción"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="inventario.proveedor",
                verbose_name="Proveedor",
            ),
        ),
    ]
