# Generated by Django 5.2.10 on 2026-07-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0032_backfill_items_impresora"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendiente",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pendientes",
                to="inventario.pedido",
                verbose_name="Pedido vinculado",
            ),
        ),
    ]
