# Generated by Django 5.2.10 on 2026-07-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0033_pendiente_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="es_patrimonial",
            field=models.BooleanField(
                default=False,
                help_text="Cada unidad cargada en un pedido va a pedir su propio N° de patrimonio.",
                verbose_name="Es patrimonial",
            ),
        ),
    ]
