# Generated by Django 5.2.10 on 2026-07-02 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0034_articulo_es_patrimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="impresora",
            name="articulo",
            field=models.ForeignKey(
                blank=True,
                help_text="Artículo patrimonial del que sale esta unidad (ej: 'Impresora Brother HL 1212').",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impresoras",
                to="inventario.articulo",
                verbose_name="Artículo de catálogo",
            ),
        ),
    ]
