# Generated by Django 5.2.10 on 2026-07-02 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0036_backfill_items_articulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="patrimoniounidad",
            name="articulo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patrimonios",
                to="inventario.articulo",
            ),
        ),
        migrations.AlterField(
            model_name="patrimoniounidad",
            name="pedido_detalle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patrimonios",
                to="inventario.pedidodetalle",
            ),
        ),
    ]
