# Generated by Django 5.2.10 on 2026-07-15 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0038_backfill_patrimonio_articulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="activopc",
            name="articulo",
            field=models.ForeignKey(
                blank=True,
                help_text="Artículo patrimonial del que sale esta unidad (ej: 'Router TP-Link Archer C6').",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activos_pc",
                to="inventario.articulo",
                verbose_name="Artículo de catálogo",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="genera_ficha",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Ninguna (solo patrimonio genérico)"),
                    ("IMPRESORA", "Impresora"),
                    ("ACTIVO_PC", "Activo PC / equipo de red"),
                ],
                default="",
                help_text="Al cargar el N° de patrimonio de una unidad, crear automáticamente su ficha completa (impresora / equipo).",
                max_length=20,
                verbose_name="Genera ficha de",
            ),
        ),
    ]
