# Generated by Django 5.2.1 on 2026-07-20 15:14

import django.db.models.deletion
from django.db import migrations, models


def migrar_numero_nota_a_fk(apps, schema_editor):
    """
    Antes, 'numero_nota' era texto libre. Si coincide exactamente con el
    número de alguna Nota ya cargada, vinculamos el pedido a esa nota.
    """
    Pedido = apps.get_model("inventario", "Pedido")
    Nota = apps.get_model("inventario", "Nota")

    for pedido in Pedido.objects.exclude(numero_nota=""):
        numero = pedido.numero_nota.strip()
        if not numero:
            continue
        coincidencias = list(Nota.objects.filter(numero=numero))
        if len(coincidencias) == 1:
            pedido.nota = coincidencias[0]
            pedido.save(update_fields=["nota"])


def revertir_fk_a_numero_nota(apps, schema_editor):
    Pedido = apps.get_model("inventario", "Pedido")
    for pedido in Pedido.objects.exclude(nota__isnull=True):
        pedido.numero_nota = pedido.nota.numero
        pedido.save(update_fields=["numero_nota"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0039_activopc_articulo_articulo_genera_ficha"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="nota",
            field=models.ForeignKey(
                blank=True,
                help_text="Nota previamente cargada a la que corresponde este pedido (opcional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="inventario.nota",
                verbose_name="Nota vinculada",
            ),
        ),
        migrations.RunPython(migrar_numero_nota_a_fk, revertir_fk_a_numero_nota),
        migrations.RemoveField(
            model_name="pedido",
            name="numero_nota",
        ),
    ]
