# Generated by Django 5.2.1 on 2026-07-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0040_pedido_nota_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="patrimoniounidad",
            name="donante",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Donado por"
            ),
        ),
        migrations.AddField(
            model_name="patrimoniounidad",
            name="donante_contacto",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Contacto del donante"
            ),
        ),
        migrations.AddField(
            model_name="patrimoniounidad",
            name="es_donacion",
            field=models.BooleanField(default=False, verbose_name="Es donación"),
        ),
    ]
