# Generated by Django 5.2.1 on 2026-07-21 14:26

from django.db import migrations, models


def renombrar_estados_viejos(apps, schema_editor):
    """
    El flujo de Nota cambió: APROBADA -> RECIBIDA, CERRADA -> FINALIZADA.
    Convierte las filas existentes al nuevo esquema de estados.
    """
    Nota = apps.get_model("inventario", "Nota")
    Nota.objects.filter(estado="APROBADA").update(estado="RECIBIDA")
    Nota.objects.filter(estado="CERRADA").update(estado="FINALIZADA")


def revertir_estados_viejos(apps, schema_editor):
    Nota = apps.get_model("inventario", "Nota")
    Nota.objects.filter(estado="RECIBIDA").update(estado="APROBADA")
    Nota.objects.filter(estado="FINALIZADA").update(estado="CERRADA")


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0041_patrimoniounidad_donante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="fecha_entrega_mesa_entrada",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de entrega a Mesa de Entrada"
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("ENVIADA", "Enviada"),
                    ("RECIBIDA", "Recibida"),
                    ("ENTREGADA_MESA_ENTRADA", "Entregada a Mesa de Entrada"),
                    ("FINALIZADA", "Finalizada"),
                    ("CANCELADA", "Cancelada"),
                ],
                db_index=True,
                default="BORRADOR",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="fecha_cierre",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de finalización"
            ),
        ),
        migrations.RunPython(renombrar_estados_viejos, revertir_estados_viejos),
    ]
