# Generated by Django 5.2.1 on 2026-07-21 14:54

from django.db import migrations, models


def copiar_servicio_solicitante_a_servicios(apps, schema_editor):
    Pedido = apps.get_model("inventario", "Pedido")
    for pedido in Pedido.objects.exclude(servicio_solicitante_id=None):
        pedido.servicios.add(pedido.servicio_solicitante_id)


def revertir_servicios_a_servicio_solicitante(apps, schema_editor):
    Pedido = apps.get_model("inventario", "Pedido")
    for pedido in Pedido.objects.all():
        primero = pedido.servicios.first()
        if primero:
            pedido.servicio_solicitante_id = primero.id
            pedido.save(update_fields=["servicio_solicitante"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0042_nota_fecha_entrega_mesa_entrada_alter_nota_estado_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="servicios",
            field=models.ManyToManyField(
                related_name="pedidos", to="inventario.servicio"
            ),
        ),
        migrations.RunPython(
            copiar_servicio_solicitante_a_servicios,
            revertir_servicios_a_servicio_solicitante,
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="servicio_solicitante",
        ),
    ]
