# Generated by Django 5.2.1 on 2026-07-22 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0043_remove_pedido_servicio_solicitante_pedido_servicios"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Intercambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detalle_saliente",
                    models.CharField(
                        blank=True,
                        help_text="Si el ítem no tiene N° de patrimonio, describilo acá.",
                        max_length=255,
                    ),
                ),
                ("motivo", models.TextField(blank=True, default="")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("RESUELTO", "Resuelto"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_intercambio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("detalle_entrante", models.CharField(blank=True, max_length=255)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intercambios_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patrimonio_entrante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intercambios_como_entrante",
                        to="inventario.patrimoniounidad",
                    ),
                ),
                (
                    "patrimonio_saliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intercambios_como_saliente",
                        to="inventario.patrimoniounidad",
                    ),
                ),
                (
                    "resuelto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intercambios_resueltos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servicio_afectado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intercambios_a_favor",
                        to="inventario.servicio",
                        verbose_name="Servicio que espera compensación",
                    ),
                ),
                (
                    "servicio_beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intercambios_recibidos",
                        to="inventario.servicio",
                        verbose_name="Servicio que se queda con el equipo",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_intercambio"],
            },
        ),
    ]
