# Generated by Django 5.2.1 on 2026-07-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0044_intercambio"),
    ]

    operations = [
        migrations.AddField(
            model_name="intercambio",
            name="pedido_entrante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intercambios_entrante",
                to="inventario.pedido",
                verbose_name="Pedido esperado para resolver el intercambio",
            ),
        ),
        migrations.AddField(
            model_name="intercambio",
            name="pedido_saliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intercambios_saliente",
                to="inventario.pedido",
                verbose_name="Pedido de donde llegó el ítem entregado",
            ),
        ),
    ]
