# Generated by Django 5.2.1 on 2026-07-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0045_intercambio_pedido_entrante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendiente",
            name="nota",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pendientes",
                to="inventario.nota",
                verbose_name="Nota vinculada",
            ),
        ),
    ]
