# Generated by Django 5.2.10 on 2026-07-30 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0046_pendiente_nota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamodetalle",
            name="cantidad",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
