# Generated by Django 5.2.1 on 2026-08-18 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0047_alter_prestamodetalle_cantidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="activopc",
            name="impresora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="computadoras",
                to="inventario.impresora",
                verbose_name="Impresora asociada",
            ),
        ),
        migrations.AddField(
            model_name="activopc",
            name="switch",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Switch / puerto de red al que está conectada (opcional).",
                max_length=100,
                verbose_name="Switch de red",
            ),
        ),
        migrations.AddField(
            model_name="activopc",
            name="usuario",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Persona que usa habitualmente esta PC (opcional).",
                max_length=120,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="impresora",
            name="dns",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Uno o más servidores DNS, separados por coma (opcional).",
                max_length=200,
                verbose_name="DNS",
            ),
        ),
        migrations.AddField(
            model_name="impresora",
            name="puerta_enlace",
            field=models.GenericIPAddressField(
                blank=True, null=True, protocol="IPv4", verbose_name="Puerta de enlace"
            ),
        ),
        migrations.AddField(
            model_name="impresora",
            name="submascara",
            field=models.GenericIPAddressField(
                blank=True, null=True, protocol="IPv4", verbose_name="Máscara de subred"
            ),
        ),
    ]
