# Generated by Django 5.2.10 on 2026-09-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0048_activopc_impresora_activopc_switch_activopc_usuario_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="impresora",
            constraint=models.UniqueConstraint(
                condition=models.Q(("patrimonio", ""), _negated=True),
                fields=("patrimonio",),
                name="uniq_impresora_patrimonio",
            ),
        ),
    ]
