# Generated by Django 5.2.10 on 2026-09-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0049_impresora_uniq_impresora_patrimonio"),
    ]

    operations = [
        migrations.AddField(
            model_name="toner",
            name="stock_minimo",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Si el stock disponible cae a este número o menos, aparece como alerta en el dashboard. 0 = sin alerta.",
                verbose_name="Stock mínimo",
            ),
        ),
    ]
