# Generated by Django 5.2.1 on 2026-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0050_toner_stock_minimo"),
    ]

    operations = [
        migrations.AddField(
            model_name="activopc",
            name="actualizado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="servicio",
            name="actualizado",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
