# Generated by Django 5.2.1 on 2026-09-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0051_activopc_actualizado_servicio_actualizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="impresora",
            name="mac",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ej: 00:1A:2B:3C:4D:5E (opcional).",
                max_length=17,
                verbose_name="Dirección MAC",
            ),
        ),
    ]
