# Generated by Django 5.2.10 on 2026-10-01 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0052_impresora_mac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
