# Generated by Django 5.2.10 on 2026-10-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0053_alter_nota_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impresora",
            name="tipo",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
