from .core import *
from .reportes import *
from .toner import *
from .articulos import *
from .pcs import *
from .servicios import *
from .impresoras import *
from .movimientos import *
from .prestamos import *
from .pendientes import *
from .reparaciones import *
from .pedidos import *
from .patrimonios import *
from .notas import *
from .admin import *
